language: c
compiler:
  - clang
  - gcc
before_install:
  - "sudo apt-get -qq update"
  - "if [ ! $CC = 'clang' ]; then sudo apt-get -qq install qemu-system libc6:i386; fi"
  - "if [ ! $CC = 'clang' ]; then
        TOOLCHAIN_NAME='arm-2013.05';
        TOOLCHAIN_TARBALL=${TOOLCHAIN_NAME}-23-arm-none-eabi-i686-pc-linux-gnu.tar.bz2;
        TOOLCHAIN_URL=https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/${TOOLCHAIN_TARBALL};
        curl $TOOLCHAIN_URL | sudo tar xj -C /usr/;
        export PATH=/usr/${TOOLCHAIN_NAME}/bin:$PATH;
        arm-none-eabi-gcc --version;
    fi"
  - "if [ ! $CC = 'clang' ]; then sudo apt-get -qq install gcc-msp430 msp430-libc msp430mcu; fi"
  - "if [ ! $CC = 'clang' ]; then sudo apt-get -qq install gcc-avr avr-libc; fi"
script:
  - "make -C src libxively"
  - "make -C src tests XI_UNIT_TEST_TARGET=native"
  - "if [ ! $CC = 'clang' ]; then make -C src tests XI_UNIT_TEST_TARGET=cortex-m3-qemu; fi"
  - "if [ ! $CC = 'clang' ]; then make ci_msp430; fi"
  - "if [ ! $CC = 'clang' ]; then make ci_avr; fi"
